name: NodeJS with Webpack

on:
  push:
    branches:
      - develop

jobs:
  deploy-backend-dev:
    name: Deploy Backend to Dev
    runs-on: ubuntu-latest
    environment: development
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: yarn
    steps:
      - run: echo 'hello world'        
  

    
